// Pattern Registry - All AI detection patterns with weights
import { Pattern, Severity } from '../types';

export const SEVERITY_WEIGHTS: Record<Severity, number> = {
  CRITICAL: 15,
  HIGH: 8,
  MEDIUM: 4,
  LOW: 2,
  VERY_LOW: 1,
  INFORMATIONAL: 0.2,
};

const PLACEHOLDER_TEMPLATE_REGEX = new RegExp(
  [
    '\\b(?:[Ii]nsert|[Ee]nter)\\s+(?:[A-Za-z0-9_]+\\s*)[Hh]ere\\b',
    '(?:\\[(?!PLACEHOLD\\])[A-Z0-9 _]+\\]|\\{[A-Z0-9 _]+\\}|<[A-Z0-9 _]+>)',
    '\\b[Pp][Ll][Aa][Cc][Ee][Hh][Oo][Ll][Dd][Ee][Rr]\\b',
    '\\[(?:[Pp][Ll][Aa][Cc][Ee][Hh][Oo][Ll][Dd][Ee][Rr](?:\\s+[Tt][Ee][Xx][Tt])?)\\]',
    '\\b(?:REPLACE_ME|REPLACE THIS|TO_BE_FILLED|TO BE FILLED)\\b',
    '\\b(?:TBD|TBA|[Tt]o be [Dd]etermined|[Tt]o be [Aa]nnounced)\\b',
    '\\b[Ll]orem\\s+[Ii]psum\\b',
    '\\b(?:[Ff]oo|[Bb]ar|[Bb]az|[Qq]ux)\\b',
    '\\b(?:[Tt]est\\s+[Uu]ser|[Tt]est\\s+[Aa]ccount)\\b',
    '\\b(?:John\\s+Doe|Jane\\s+Doe|A\\.?\\s*N\\.?\\s*Other|AN\\s+Other|Ann\\s+Other)\\b',
    '\\b[Yy]our\\s+[A-Za-z0-9_ ]+\\s+[Hh]ere\\b',
    '\\b(?:[A-Za-z]+(?:Company|Organization|Location|City|State|Country|Realm|Nation)s?)\\b',
    '(?:__+|—{2,}|–{2,})',
    '(?:\\[[^\\]]*\\.{3,}[^\\]]*\\]|\\{[^}]*\\.{3,}[^}]*\\}|<[^>]*\\.{3,}[^>]*>)',
    '\\([\\s\\-–—]{2,}\\)',
    '(?:Name|Title|Location|Role|Date|Time)\\s*:\\s*__+',
  ].join('|'),
  'gu'
);

export const REPETITION_WORDS = ['also', 'various', 'however', 'because', 'therefore', 'although', 'moreover', 'furthermore', 'indeed', 'notably', 'specifically', 'importantly', 'consequently', 'additionally', 'alternatively', 'essentially', 'arguably', 'ultimately', 'generally', 'meanwhile', 'nevertheless', 'nonetheless', 'thus', 'hence', 'accordingly', 'similarly', 'likewise'];
export const REPETITION_BIGRAMS = [
  'lay ahead',
  'let us',
  'it should',
  'based on',
  'plays a',
  'crucial role',
  'paves the',
  'testament to',
  "in today's",
  'driven by',
  'designed to',
  'aims to',
  'leverage the',
  'harness the',
  'ensure that',
  'as a result',
  'i hope',
  'let me',
  'feel free',
  'thank you',
  'looking forward',
  'just wanted',
  'please let',
  'reach out',
  'get back',
  'touch base',
  'data analysis',
  'as shown',
  'results show',
  'our findings',
  'the model',
];
export const REPETITION_TRIGRAMS = [
  'as well as',
  'in order to',
  'it is important',
  'it is crucial',
  'it is essential',
  'it is worth',
  'it is clear',
  'based on the',
  'as a result',
  'as mentioned earlier',
  'on the other',
  'this means that',
  'this can be',
  'this is because',
  'in the context',
  'plays a crucial',
  'plays a vital',
  'a testament to',
  'designed to enhance',
  'i hope this',
  'hope this email',
  'looking forward to',
  'driven by innovation',
  'in the realm',
];

export const PATTERNS: Pattern[] = [
  // CRITICAL patterns - definitive AI signals
  {
    id: 'ai-self-reference',
    name: 'AI Self-Reference',
    description: 'Explicit AI self-identification phrases',
    regex: /as an AI (language model|assistant|model)/gi,
    severity: 'CRITICAL',
    weight: SEVERITY_WEIGHTS.CRITICAL,
    examples: ['as an AI language model', 'as an AI assistant'],
  },
  {
    id: 'knowledge-cutoff',
    name: 'Knowledge Cutoff Disclaimer',
    description: 'References to AI training data cutoffs',
    regex: /as (of|at) my (last|latest) (update|training|knowledge)/gi,
    severity: 'CRITICAL',
    weight: SEVERITY_WEIGHTS.CRITICAL,
    examples: ['as of my last update', 'as at my latest training'],
  },

  // HIGH severity patterns
  {
    id: 'significance-statement',
    name: 'Significance Statement',
    description: 'Significance statements commonly used in AI text',
    regex: /(stands|serves) as a (testament|symbol)/gi,
    severity: 'HIGH',
    weight: SEVERITY_WEIGHTS.HIGH,
    examples: ['stands as a testament to', 'serves as a symbol of'],
  },
  {
    id: 'placeholder-template',
    name: 'Placeholder Template',
    description: 'Placeholder text patterns',
    regex: PLACEHOLDER_TEMPLATE_REGEX,
    severity: 'HIGH',
    weight: SEVERITY_WEIGHTS.HIGH,
    examples: [
      'insert name here',
      '[PLACEHOLDER]',
      '[placeholder text]',
      'PLACEHOLDER',
      'lorem ipsum',
      'Test User',
      '[TOPIC]',
    ],
  },
  {
    id: 'collaborative-certainly',
    name: 'Collaborative: Certainly',
    description: 'Overly helpful collaborative phrases',
    regex: /(certainly!|of course!)/gi,
    severity: 'HIGH',
    weight: SEVERITY_WEIGHTS.HIGH,
    examples: ['Certainly!', 'Of course!'],
  },
  {
    id: 'collaborative-would-you',
    name: 'Collaborative: Would You Like',
    description: 'Offering further assistance',
    regex: /would you like/gi,
    severity: 'HIGH',
    weight: SEVERITY_WEIGHTS.HIGH,
    examples: ['would you like me to explain'],
  },
  {
    id: 'collaborative-let-me-know',
    name: 'Collaborative: Let Me Know',
    description: 'Requesting feedback or clarification',
    regex: /let me know if/gi,
    severity: 'HIGH',
    weight: SEVERITY_WEIGHTS.HIGH,
    examples: ['let me know if you need', 'let me know if this helps'],
  },
  {
    id: 'collaborative-here-is',
    name: 'Collaborative: Here Is',
    description: 'Presenting information formally',
    regex: /\bhere(?:'s| is) a/gi,
    severity: 'HIGH',
    weight: SEVERITY_WEIGHTS.HIGH,
    examples: ["here's a summary", 'here is a breakdown'],
  },
  {
    id: 'collaborative-hope-helps',
    name: 'Collaborative: I Hope This Helps',
    description: 'Closing with helpful intent',
    regex: /I hope this helps/gi,
    severity: 'HIGH',
    weight: SEVERITY_WEIGHTS.HIGH,
    examples: ['I hope this helps!'],
  },
  {
    id: 'data-analysis-actionable-insights',
    name: 'Data Analysis: Actionable Insights',
    description: 'AI-generated data analysis jargon phrase',
    regex: /[""]?deliver\s+actionable\s+insights\s+through\s+in(?:-|\s)?depth\s+data\s+analysis[""]?/iu,
    severity: 'HIGH',
    weight: SEVERITY_WEIGHTS.HIGH,
    examples: ['deliver actionable insights through in-depth data analysis'],
  },
  {
    id: 'data-analysis-driven-decisions',
    name: 'Data Analysis: Data-Driven Decisions',
    description: 'AI-generated data-driven decisions phrase',
    regex: /[""]?drive\s+insightful\s+data(?:-|\s)?driven\s+decisions[""]?/iu,
    severity: 'HIGH',
    weight: SEVERITY_WEIGHTS.HIGH,
    examples: ['drive insightful data-driven decisions'],
  },
  {
    id: 'data-analysis-leverage-insights',
    name: 'Data Analysis: Leverage Insights',
    description: 'AI-generated leveraging data insights phrase',
    regex: /[""]?leverag(?:e|ing)\s+data(?:-|\s)?driven\s+insights[""]?/iu,
    severity: 'HIGH',
    weight: SEVERITY_WEIGHTS.HIGH,
    examples: ['leveraging data-driven insights'],
  },
  {
    id: 'data-analysis-extract-insights',
    name: 'Data Analysis: Extract Meaningful Insights',
    description: 'AI-generated extract insights from datasets phrase',
    regex: /[""]?leverag(?:e|ing)\s+complex\s+datasets\s+to\s+extract\s+meaningful\s+insights[""]?/iu,
    severity: 'HIGH',
    weight: SEVERITY_WEIGHTS.HIGH,
    examples: ['leveraging complex datasets to extract meaningful insights'],
  },
  {
    id: 'most-overused',
    name: 'Most Overused AI Phrases',
    description: 'Highly characteristic overused AI phrases and words',
    regex: /\b(?:as an (?:ai|large(?:\s+language)?) model|it(?:'|'| i)s critical to|tapestry|i hope this (?:email|message)? finds you well|crucial)\b/iu,
    severity: 'HIGH',
    weight: SEVERITY_WEIGHTS.HIGH,
    examples: ['as an AI model', "it's critical to", 'I hope this email finds you well', 'tapestry'],
  },
  {
    id: 'business-jargon',
    name: 'Business and Tech Jargon',
    description: 'Corporate and technical buzzwords commonly used by AI',
    regex: /\b(?:bandwidth|governance framework|stakeholders?|kpis?|roi|mvp|poc|sla|tco|value proposition|best practices|pain points?|touchpoints?|deliverables?|scalable?|state-of-the-art|game-changer|paradigm shifts?|synergy|thought leaders?|disruptive innovation)\b/iu,
    severity: 'HIGH',
    weight: SEVERITY_WEIGHTS.HIGH,
    examples: ['bandwidth', 'stakeholders', 'value proposition', 'scalable', 'paradigm shift', 'synergy'],
  },

  // MEDIUM severity patterns
  {
    id: 'cultural-cliche',
    name: 'Cultural Heritage Cliché',
    description: 'Overused cultural heritage phrases',
    regex: /rich (cultural|historical) (heritage|tapestry)/gi,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['rich cultural heritage', 'rich historical tapestry'],
  },
  {
    id: 'negative-parallelism',
    name: 'Negative Parallelism',
    description: 'Not only...but also constructions',
    regex: /not (just|only).{1,50}but (also|rather)/gi,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['not just affordable but also sustainable'],
  },
  {
    id: 'challenges-prospects',
    name: 'Challenges and Prospects',
    description: 'Formulaic challenges sections',
    regex: /despite (its|these) challenges/gi,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['despite these challenges', 'despite its challenges'],
  },
  {
    id: 'vague-attribution',
    name: 'Vague Attribution',
    description: 'Vague citations without specifics',
    regex: /(studies|research|experts) (show|suggest|indicate)/gi,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['studies show that', 'research suggests'],
  },
  {
    id: 'worth-mentioning',
    name: 'Worth Mentioning',
    description: 'Editorializing phrase for emphasis',
    regex: /worth mentioning/gi,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['worth mentioning that', 'it is worth mentioning'],
  },
  {
    id: 'ai-stock-phrases',
    name: 'AI Stock Phrases',
    description: 'Common editorial and disclaimer phrases used by AI',
    regex: /(?:\bit(?:'|'| i)s important to (?:note|remember|consider|understand) (?:that)?|\bon the contrary\b|\bthis is not an exhaustive list\b)\s*(?:\.\.\.|…)?[^\S\r\n]*[.)!?]*/iu,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ["it's important to note that", 'this is not an exhaustive list', 'on the contrary'],
  },
  {
    id: 'communication-styles',
    name: 'AI Communication Style Patterns',
    description: 'Formal transitional and connective phrases typical of AI writing',
    regex: /\b(?:remember that(?:\.\.\.|…)?|furthermore|specifically|importantly|notably|despite|essentially|alternatively|even though|because|in contrast|although|due to|given that|you may want to|on the other hand|as previously mentioned|to summarize|ultimately|to put it simply|as such|for (?:example|instance)|generally speaking|going forward|in (?:brief|detail|effect|essence|general|light of|other words|particular|practice|terms of|theory)|namely|that being said|to (?:clarify|demonstrate|emphasize|illustrate|reiterate|shed light on)|with regards to|whilst)\b/iu,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['furthermore', 'as a result', 'for example', 'generally speaking', 'in essence', 'that being said'],
  },
  {
    id: 'action-words',
    name: 'Dramatic Action Words',
    description: 'Overly dramatic or flowery action verbs favored by AI',
    regex: /\b(?:navigat(?:e|ing)|dive|tailored|embark|unlock the secrets|unveil the secrets|elevate|unleash|harness|delve into|take a dive into|master(?:y|ing)?|excels|imagine|dive into|enhance|emphas(?:is|ise|ize|ising|izing|ised|ized)|revolutioniz(?:e|es|ed|ing)|foster|subsequently|whisper(?:s|ing)?|reverberat(?:e|es|ed|ing)|promptly|amplify|enable|enriches?|explore|glean|promote|recognize|resonate|showcas(?:e|ing)|streamline|strive|thrive|thriving|brace(?:s|d|ing)?|discover(?:s|ed|ing)?|emerge(?:s|d|ing)?|envision(?:s|ed|ing)?|galvaniz(?:e|es|ed|ing)|redefine(?:s|d|ing)?|reinforce(?:s|d|ing)?|transcend(?:s|ed|ing)?|usher(?:s|ed|ing)?)\b/iu,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['unlock the secrets', 'delve into', 'harness', 'revolutionize', 'elevate', 'amplify', 'streamline', 'envision', 'transcend', 'galvanize'],
  },
  {
    id: 'contextual-phrases',
    name: 'AI Contextual Phrases',
    description: 'Common contextual framing phrases used by AI',
    regex: /\b(?:the world of|in today(?:'|'|)s (?:digital (?:age|era)|world|rapidly evolving market)|designed to enhance|it is advisable|when it comes to|in the realm of|in the world of|in the dynamic world of|as a professional|however|therefore|generally|while|unless|in order to|even if|my friend|in conclusion|hey|game[-\s]?changer|landscape|testament|firstly|moreover|to consider|there are a few considerations|ensure|it(?:'|'| i)s essential to|as well as|sights unseen|sounds unheard|remnant|nestled|folks|at the end of the day|digital realm|the (?:future|power|road ahead) of|uncharted waters|(?:reaching )?new heights|the next frontier)\b/iu,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['in the world of', "in today's digital age", 'when it comes to', 'at the end of the day', 'digital realm', 'uncharted waters'],
  },
  {
    id: 'conductor-music-analogy',
    name: 'Conductor/Orchestra Metaphor',
    description: 'Overused conductor and orchestration metaphors typical of AI',
    regex: /(?:\b(?:like|as|akin to)\s+(?:a\s+)?(?:conductor|maestro)\b|\b(?:orchestrate|orchestrating|orchestration|symphony|harmon(?:y|ious|ize|izing)|crescendo)\b)/iu,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['like a conductor', 'orchestrate', 'symphony', 'harmonize'],
  },
  {
    id: 'hyperbolic-phrases',
    name: 'Hyperbolic Impact Phrases',
    description: 'Exaggerated impact and barrier-breaking phrases',
    regex: /\b(?:break(?:ing)?\s+barriers?|cannot be overstated|unwavering)\b/iu,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['break barriers', 'cannot be overstated', 'unwavering'],
  },
  {
    id: 'additional-connectives',
    name: 'Additional Connective Phrases',
    description: 'More transitional and connective words common in AI writing',
    regex: /\b(?:conversely|along with|amidst|towards)\b/iu,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['conversely', 'along with', 'amidst', 'towards'],
  },
  {
    id: 'empowerment-verbs',
    name: 'Empowerment Action Verbs',
    description: 'Motivational and empowerment verbs favored by AI',
    regex: /\b(?:empower(?:s|ed|ing)?|embrace(?:s|d|ing)?|grasp(?:s|ed|ing)?|hinder(?:s|ed|ing)?)\b/iu,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['empower', 'embrace', 'grasp', 'hinder'],
  },
  {
    id: 'deep-noun-pattern',
    name: 'Deep + Noun Construction',
    description: 'AI tendency to use "deep" with abstract nouns',
    regex: /\bdeep\s+(?:understanding|insights?|knowledge|analysis|dive|exploration|connection|impact|meaning|significance)\b/iu,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['deep understanding', 'deep insights', 'deep dive', 'deep analysis'],
  },
  {
    id: 'hustle-and-bustle',
    name: 'Hustle and Bustle Cliché',
    description: 'Overused urban energy cliché phrase',
    regex: /\bhustle\s+and\s+bustle\b/iu,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['hustle and bustle'],
  },
  {
    id: 'quantity-phrases',
    name: 'Quantity and Abundance Phrases',
    description: 'Phrases emphasizing quantity or abundance',
    regex: /\b(?:a (?:journey|multitude|plethora|treasure trove) of|(?:ample|manifold) opportunities)\b/iu,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['a plethora of', 'a multitude of', 'a journey of', 'manifold opportunities'],
  },
  {
    id: 'significance-intensifiers',
    name: 'Significance Intensifiers',
    description: 'Words and phrases that intensify importance or impact',
    regex: /\b(?:paramount|pivotal|undeniable|unparalleled|demonstrates significant|cannot be overstated|(?:linchpin|epicenter) of)\b/iu,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['paramount', 'pivotal', 'undeniable', 'demonstrates significant', 'linchpin of'],
  },

  // INFORMATIONAL severity patterns
  {
    id: 'transitional-words',
    name: 'AI Transitional Words',
    description: 'Formal transitional words commonly overused by AI',
    regex: /\b(accordingly|additionally|arguably|certainly|consequently|equally|hence|however|indeed|moreover|nevertheless|nonetheless|notwithstanding|thus|undoubtedly)\b[^\S\r\n]*[.,;:!?)]?/iu,
    severity: 'INFORMATIONAL',
    weight: SEVERITY_WEIGHTS.INFORMATIONAL,
    examples: ['accordingly,', 'moreover', 'nevertheless'],
  },

  // VERY LOW severity patterns
  {
    id: 'ai-adjectives',
    name: 'AI-Favored Adjectives',
    description: 'Adjectives frequently overused by AI models',
    regex: /\b(adept|commendable|dynamic|efficient|ever(?:-|\s)evolving|exciting|exemplary|innovative|invaluable|robust|seamless|synergistic|thought(?:-|\s)provoking|transformative|utmost|vibrant|vital|agile|arduous|burgeoning|captivating|cognizant|considerable|esteemed|flourishing|granularly?|groundbreaking|holistically?|impactful|multifaceted|nuanced|numerous|rapidly evolving|relentless|remarkable|substantial|systemic|well(?:-|\s)crafted|avant(?:-|\s)garde|distinguished|exquisite|formidable|game(?:-|\s)changing|iconic|indomitable|irrefutable|omniscient|paradigm(?:-|\s)shifting|pioneering|predominant|profound|prominent|quintessential|revolutionary|tangible|trailblazing|ubiquitous|unassailable|unblemished|unequaled|unmatched|unrivaled|unsurpassed|unyielding|visionary)\b/iu,
    severity: 'VERY_LOW',
    weight: SEVERITY_WEIGHTS.VERY_LOW,
    examples: ['robust', 'seamless', 'innovative', 'holistic', 'nuanced', 'multifaceted', 'groundbreaking', 'quintessential', 'visionary', 'paradigm-shifting'],
  },
  {
    id: 'ai-nouns',
    name: 'AI-Favored Nouns',
    description: 'Abstract nouns commonly used by AI',
    regex: /\b(efficiency|innovation|institution|integration|implementation|landscape|optimization|realm|transformation|aforementioned|core|craft|expertise|insights?|kaleidoscope|latency|milestone|paradigm|plethora|sustainability|uptime|various|vast|apogee|epitome|facets?|gusto|nexus|odyssey|panorama|pinnacle|spectrum|trajectory)s?\b[^\S\r\n]*[.,;:!?)]?/iu,
    severity: 'VERY_LOW',
    weight: SEVERITY_WEIGHTS.VERY_LOW,
    examples: ['landscape', 'realm', 'expertise', 'paradigm', 'kaleidoscope', 'epitome', 'odyssey', 'pinnacle', 'nexus'],
  },
  {
    id: 'ai-verbs',
    name: 'AI-Favored Verbs',
    description: 'Formal verbs commonly overused by AI',
    regex: /\b(aligns?|augment(?:s|ing|ed)?|facilitat(?:e|es|ed|ing)|maximiz(?:e|es|ed|ing)|underscor(?:e|es|ed|ing)|utili[sz](?:e|es|ed|ing))\b[^\S\r\n]*[.,;:!?)]?/iu,
    severity: 'VERY_LOW',
    weight: SEVERITY_WEIGHTS.VERY_LOW,
    examples: ['facilitate', 'underscore', 'align', 'augment'],
  },
  {
    id: 'ai-descriptors',
    name: 'AI Descriptive Words',
    description: 'Flowery descriptors and complex vocabulary favored by AI',
    regex: /\b(?:meticulous|complexity|complexities|realms?|understanding|ever(?:-|\s)changing|ever(?:-|\s)evolving|daunting|cutting(?:-|\s)edge|robust|power|bustling|vibrant|metropolis|essential|keen|fancy|labyrinthine?|gossamer|enigma|indelible|dedication|moist|key|valuable|herein|heretofore|therein|thereof|enlightening|entrenched|fresh perspectives?|in a sea of|golden ticket)\b/iu,
    severity: 'VERY_LOW',
    weight: SEVERITY_WEIGHTS.VERY_LOW,
    examples: ['meticulous', 'ever-evolving', 'cutting-edge', 'labyrinthine', 'gossamer', 'key', 'fresh perspectives'],
  },
  {
    id: 'repetition-ngrams',
    name: 'Repetition Pattern',
    description: 'Repeated words, bigrams, or trigrams across the text',
    regex: /\b\B/,
    severity: 'VERY_LOW',
    weight: SEVERITY_WEIGHTS.VERY_LOW,
    examples: ['also', 'lay ahead', 'as well as'],
  },
  {
    id: 'ritual-conclusion',
    name: 'Ritual Conclusion',
    description: 'Formulaic conclusion phrases',
    regex: /^(in summary|overall|in conclusion)/gim,
    severity: 'LOW',
    weight: SEVERITY_WEIGHTS.LOW,
    examples: ['In summary', 'Overall', 'In conclusion'],
  },
  {
    id: 'artificial-range',
    name: 'Artificial Range',
    description: 'From X to Y range patterns',
    regex: /from .{3,20} to .{3,20}/gi,
    severity: 'LOW',
    weight: SEVERITY_WEIGHTS.LOW,
    examples: ['from beginners to experts', 'from design to deployment'],
  },
  {
    id: 'profound-legacy',
    name: 'Profound Legacy',
    description: 'Cultural heritage cliché about lasting impact',
    regex: /profound legacy/gi,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['profound legacy of', 'left a profound legacy'],
  },
  {
    id: 'broken-citation',
    name: 'Broken Citation',
    description: 'Placeholder citations',
    regex: /\[(citation needed|source)\]/gi,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['[citation needed]', '[source]'],
  },
  {
    id: 'emoji-heading',
    name: 'Emoji in Heading',
    description: 'Emoji characters in markdown-style headings',
    regex: /^#+\s+.*[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gmu,
    severity: 'MEDIUM',
    weight: SEVERITY_WEIGHTS.MEDIUM,
    examples: ['# 🎯 Getting Started', '## 🚀 Features'],
  },
  {
    id: 'title-case-heading',
    name: 'Title Case Heading',
    description: 'Excessive title case in headings',
    regex: /^#+\s+([A-Z][a-z]+\s+){3,}/gm,
    severity: 'LOW',
    weight: SEVERITY_WEIGHTS.LOW,
    examples: ['# The Complete Guide To Modern Development', '## Best Practices For Writing Code'],
  },
  {
    id: 'em-dash-spam',
    name: 'Em-Dash Spam',
    description: 'Excessive use of em-dashes',
    regex: /(—.*){3,}/g,
    severity: 'LOW',
    weight: SEVERITY_WEIGHTS.LOW,
    examples: ['text—more text—even more—and more'],
  },
];

export function getPatternById(id: string): Pattern | undefined {
  return PATTERNS.find((p) => p.id === id);
}

export function getPatternsBySeverity(severity: Severity): Pattern[] {
  return PATTERNS.filter((p) => p.severity === severity);
}

export const PATTERN_ENGINE_VERSION = '1.4.0';
